### PR TITLE
client.networks.create check_duplicates docs not reflective of behavior

### LINKED ISSUE #1693: client.networks.create check_duplicates docs not reflective of behavior
Docs say it does, but it's actually set to `None`.

### PR DESCRIPTION
**Pull request by dimaspivak**
Fixes #1693

### CODE REVIEW

**Comment by shin-** [comment]
We want to defer the default value to the Engine if possible, so I think we should keep `None` here, and update the docs instead to reflect the actual behavior.

**Comment by dimaspivak** [comment]
My concern is that, as it stands, duplicate networks get created (by default) whereas they're not created by default from the Docker CLI. But if that's the expected behavior, we can close this.

**Comment by shin-** [comment]
I think that's fine - the definitive reference is the engine API, not the CLI.

**Comment by shin-** [comment]
Thanks!

**Pull request merged**
