### PR TITLE
Add assert_fingerprint option.

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: dlorenc <lorenc.d@gmail.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
Ping :)

**Comment by shin-** [comment]
Thanks! I'll look into this when preparing the next release &ndash; sorry for the delay.

**Comment by dlorenc** [comment]
Hey, any idea when the next release will be?

**Comment by shin-** [comment]
Sorry, I don't have an ETA right now. My time is focused on a different project at the moment, but I will have more leeway by the end of the month.

**Comment by shin-** [comment]
Thank you for your patience. =)

**Pull request merged**
