### PR TITLE
added simple support for propagation in bind mounts

### PR DESCRIPTION
**Pull request by jannefleischer**
For autofs-support in Jupyterhub I needed propagation support in bind mounts. So I added this.

Though I don't know if you want it in here, due to the lack of Docker Desktop support.

### CODE REVIEW

**Review by milas — APPROVED** [review]
LGTM, thanks!

**Review by milas — CHANGES_REQUESTED** [review]
Ah, spoke too soon. The flake8 lint job is failing. If you fix the issues there, I'll get this merged

**Comment by milas** [comment]
Thanks for the PR and fixes - this is merged via 0f0b20a6a79cfdfc9aa2747bd8399f302742cbe2.

(Apologies for any noise/confusion, I had to rebase and do some Git shenanigans 😓)

**Comment by jannefleischer** [comment]
Thanks!

**Pull request closed without merging**
