### PR TITLE
Update the test_inspect_network

### PR DESCRIPTION
**Pull request by wenchma**
This  is depended by https://github.com/docker/docker/pull/18928

Related to docker/docker#18626

Signed-off-by: Wen Cheng Ma <wenchma@cn.ibm.com>

### CODE REVIEW

**Comment by wenchma** [comment]
This PR and docker/docker#18928 depend on each other, so it will block each other. I workaround it that firstly we remove `test_inspect_network` temporarily, once docker/docker#18928 is merged, I can revert the remove and update the test.  wdyt ? @shin-

**Comment by shin-** [comment]
Maybe change the test instead so that it tests a few specific values in the result - I would check for the presence (and validity) of `Name`, `Id` and `Driver` in particular. That would prevent the current deadlock as well.

**Comment by wenchma** [comment]
@shin- good idea, :+1:   already updated the PR to cover only a few specific values.

**Comment by shin-** [comment]
Thanks - LGTM!

**Pull request merged**
