### PR TITLE
Add docker.api to setup packages

### PR DESCRIPTION
**Pull request by ibuildthecloud**
`docker.api` package was missing from setup.py

### CODE REVIEW

**Comment by shin-** [comment]
What would be an example of a use-case where accessing this package directly is necessary?

**Comment by ibuildthecloud** [comment]
Great question... our stuff fails on master because it can't find api.  Are you saying this package does not need to be installed?

**Comment by ibuildthecloud** [comment]
@shin- Seems to be referenced from here: https://github.com/docker/docker-py/blob/4475310eeac905e0def4e0eeec6f3573a65bb028/docker/client.py#L25

**Comment by shin-** [comment]
Did you install the package from pypi? Which version of Python are you using? I'm not seeing any issues with a fresh install on 2.7 or 3.4 :/

**Comment by ibuildthecloud** [comment]
The issue is with master only, so git clone and `setup.py install`.  1.4.0 is fine because `api` didn't exist.

**Comment by ibuildthecloud** [comment]
```python
.tox/py27/local/lib/python2.7/site-packages/docker/__init__.py:20: in <module>
    from .client import Client, AutoVersionClient # flake8: noqa
.tox/py27/local/lib/python2.7/site-packages/docker/client.py:25: in <module>
    from . import api
E   ImportError: cannot import name api
```

**Comment by shin-** [comment]
Ah, you're right. I was confused, sorry.

**Pull request merged**
