### PR TITLE
Fix win32pipe.WaitNamedPipe throw exception in windows container

### PR DESCRIPTION
**Pull request by SLdragon**
WaitNamedPipe API call in the npipesocket.py module doesn't work correctly from inside a Windows container.
This is because currently WaitNamedPipeis not supported from inside of Windows Containers (however CreateNamedPipeClient works ok). It fails with ERROR_FILE_NOT_FOUND

related issues: 
https://github.com/docker/docker-py/issues/2018
https://github.com/docker/compose/issues/5934
https://github.com/docker/for-win/issues/4012
https://github.com/dotnet/corefx/issues/24594

### CODE REVIEW

**Comment by SLdragon** [comment]
ping @shin- , please help approve this pull request, thank you very much!

**Comment by romerod** [comment]
what is missing for this to be merged?

**Comment by eNettMattD** [comment]
Any update on when this can be merged?

**Comment by StefanScherer** [comment]
I have tested this PR in a Windows container with a small test environment from https://github.com/StefanScherer/dockerfiles-windows/pull/432 and it works.

Previously docker-compose just shows this error

```
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Windows. 
```

Thanks for the contribution. Ping @chris-crone @ndeloof WDYT? Is the recursion ok here for max 10 iterations?

**Comment by rumpl** [comment]
Indeed, 10 iterations seems reasonable seeing what the code was before. 

Thanks!

**Pull request merged**
