### PR TITLE
enable setting of node labels #1225

### PR DESCRIPTION
**Pull request by nathannis**
Added update_node function to enable setting labels on nodes.  This
exposes the Update a Node function from the Docker API and should
enable promoting/demoting manager nodes inside a swarm.

Signed-off-by: Nathan Shirlberg nshirlberg@labattfood.com

### CODE REVIEW

**Comment by nathannis** [comment]
This is my first contribution to this project,.  Please pardon my questions.

The tests all passed locally.  I tried to follow the style of all existing code.  I have a consumer that is functioning properly when docker-py is installed from my source.  Please let me know when this is included in a release posted to pypi so that I can switch my application from using the source copy back to using pip install.

If you have any thoughts or suggestions, please let me know.

Thanks,
Nathan

**Comment by nathannis** [comment]
Hey guys, 
  I am currently running off my fork, but would like to get back to running off of a version of docker-py from pypi.  Is there anything I can do to get this included in a future release?

**Comment by shin-** [comment]
Hi @nathannis 

Sorry for the delay on this, other priorities have cropped up since we released 1.10 . Code and docs look good to me, and you added tests too, so this looks perfect as far as I'm concerned.

I'll merge to master for the time being, and I'll update once it makes it into a release.

**Comment by nathannis** [comment]
Thanks!

**Pull request merged**
