### PR TITLE
READY FOR REVIEW - Move image/container ID resolution to @check_resource decorator.

### PR DESCRIPTION
**Pull request by posita**
As [promised](https://github.com/docker/docker-py/pull/605#issuecomment-103903948), here's a PR moving code like this...

```py
    if isinstance(..., dict):
        ... = ....get('Id')
```

...into the `@check_resource` decorator.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
LGTM. @shin- ?

**Comment by shin-** [comment]
Mmmh, my concerns are:

* if we put it here the condition will also be unnecessarily evaluated in the case of image-oriented functions. Seems like a bad practice even though the overhead is negligible.
* I'd rather have several short, one-purpose decorators than a long, single, multi-purpose one.

**Comment by posita** [comment]
> I'd rather have several short, one-purpose decorators than a long, single, multi-purpose one.

I would tend to agree with this, except that these behaviors *already* seem very closely coupled throughout `client.py`. It seems (at least so far), everywhere that `@check_resource` is used, the code in the OP is repeated (or if it isn't, it was intended to be). Just look at how many places I removed those lines from `client.py`.

> if we put it here the condition will also be unnecessarily evaluated in the case of image-oriented functions. Seems like a bad practice even though the overhead is negligible.

Perhaps, but this is already the case. Well before I came along, `@check_resource` already pulled double duty between containers and images. Perhaps it makes more sense to have nearly identical, but separately named decorators for images and containers (e.g., `@check_image` and `@check_container`). I can do that, but that seems to be a more significant change than this was intended to be.

All I really meant to do here was an incremental improvement towards DRY without disturbing the status quo too much. Ultimately, it's your call whether such a thing is worth merging. Either way, the fact that the code in the OP shows up in so many places is probably indicative that *something* needs to be done.

**Comment by posita** [comment]
> I'd rather have several short, one-purpose decorators than a long, single, multi-purpose one.

I would tend to agree with this, except that these behaviors *already* seem very closely coupled throughout `client.py`. It seems (at least so far), everywhere that `@check_resource` is used, the code in the OP is repeated (or if it isn't, it was intended to be). Just look at how many places I removed those lines from `client.py`.

> if we put it here the condition will also be unnecessarily evaluated in the case of image-oriented functions. Seems like a bad practice even though the overhead is negligible.

Perhaps, but this is already the case. Well before I came along, `@check_resource` already pulled double duty between containers and images. Perhaps it makes more sense to have nearly identical, but separately named decorators for images and containers (e.g., `@check_image` and `@check_container`). I can do that, but that seems to be a more significant change than this was intended to be.

Plus, the overhead may be comparable when stacking the same two decorators everywhere:

```py
@check_container
@check_id
def attach(self, container, ...):
    ...
```

I know that wasn't your original point though.

All I really meant to do here was an incremental improvement towards DRY without disturbing the status quo too much. Ultimately, it's your call whether such a thing is worth merging. Either way, the fact that the code in the OP shows up in so many places is probably indicative that *something* needs to be done.

**Comment by shin-** [comment]
Thanks!

**Pull request merged**
