### PR TITLE
Add limit parameter to image search endpoint

### PR DESCRIPTION
**Pull request by feliperuhland**
- Add limit parameter to image search endpoint - 901f857

### CODE REVIEW

**Comment by feliperuhland** [comment]
Hi @ulyssessouza @chris-crone @shin- 

Could you please take a look?

Thanks!

**Comment by feliperuhland** [comment]
Hi @ulyssessouza @chris-crone @shin- 

Could you please take a look?

Thanks!

**Comment by feliperuhland** [comment]
Hi @ulyssessouza @shin-
Could you please take a look?

Thanks!

**Comment by feliperuhland** [comment]
Hi @ulyssessouza @shin- @aiordache 
Could you please take a look?

Thanks!

**Review by ulyssessouza — APPROVED** [review]
LGTM

**Review by aiordache — APPROVED** [review]
Thank you

**Pull request merged**
