### PR TITLE
Pass stdin data on attach

### PR DESCRIPTION
**Pull request by intrepidlemon**
Currently, there is no simple way of passing in `stdin` content into an attached container. The implementation provided by #239 did not work for me. This PR adds an additional parameter where one can pass in string or byte data to be written into the `stdin` of an attached container. 

In addition, this PR also contains: 
- Simple documentation for `stdin`
- Integration tests for `stdin`
- Unit tests for `attach`

### CODE REVIEW

**Comment by SakuraSound** [comment]
I commented in #239 about a workaround for Python 3 that was brought up by @Slix. While I would like an easier way to pass something into stdin upon creation of a container, i think the workaround is actually the right way to go about it if you want to keep your container running and accept more stdin input.

**Comment by bfirsh** [comment]
This would be great, but unfortunately we've had a pretty major API change in the development version. Would you mind rebasing, @intrepidlemon?

**Comment by intrepidlemon** [comment]
cleanup

**Comment by paddie** [comment]
@bfirsh so it seems all progress on getting an interactive container has stopped?

**Pull request closed without merging**
