### PR TITLE
1422: amend docs for put_archive, provide missing data details

### PR DESCRIPTION
**Pull request by vmindru**
#1422 pr for

### CODE REVIEW

**Comment by vmindru** [comment]
@GordonTheTurtle  what is the dco/no label?

**Comment by vmindru** [comment]
I think Jenkins failure is a bit strange, give both the error message and the type of changes this patch brings. 

VM

**Comment by shin-** [comment]
Thank you for your contribution! However, I feel like that change will make our documentation more confusing, whereas the current version at least provides a clear, supported way to use this method.

As far as the test failures are concerned, I'm investigating, but I agree that they're obviously not a result of your changes :)

**Comment by vmindru** [comment]
Hold on :) one would have no idea that he can pass an iterable object instead of simple bytes. One would have to check the source code find out you use requests in the background and figure out that he can pass an iterable object, maybe you folks give it a second thought before you close this?

**Comment by ns-cweber** [comment]
I came here specifically to figure out why `put_archive()` claims that it only supports `bytes` when it apparently supports iterable objects too?

**Pull request closed without merging**
