### PR TITLE
Persist docker authentification

### PR DESCRIPTION
**Pull request by olsaki**
- Persist docker authentication
- Compatible with CLI client's docker login

### CODE REVIEW

**Comment by olsaki** [comment]
Can someone please review this?

**Comment by aanand** [comment]
Thanks for the contribution!

First of all: @shin-, would you consider this functionality within scope for docker-py? I'm a bit nervous about writing out auth files - if the format or location ever changes, software which uses docker-py could end up breaking things, unless both docker-py and the Docker client are very careful about backwards-compatibility.

I have a few comments/questions regarding the code:

- "authentification" should be "authentication"
- The return value of `write_authconfig` is unused. Why is it there?
- We don't need both `config_path` and `config_file` variables.
- If the path doesn't exist, should we create it, rather than silently continuing?
- If the path does exist, are we *sure* that we're not overwriting any auth data that's already there? i.e have we definitely loaded it?

**Comment by olsaki** [comment]
@aanand @shin- ping. Any update on the idea of this in general? Please let me know if you think we should go ahead with this and I will continue to look into / work on the points mentioned above.

**Comment by dnephin** [comment]
I'd be ok with the idea as long as we make it opt-in. Adding a new kwarg that defaults to False, and when it's true we can write the config.

**Comment by olsaki** [comment]
@dnephin good idea. Shouldn't be a problem to do that. Waiting for input from @aanand and @shin- to proceed.

**Pull request closed without merging**
