### PR TITLE
support export and binding range of ports. 

### PR DESCRIPTION
**Pull request by vagouzhou**
when try expose/binding range of ports, as docker CLI. 

``` python
container_id = cli.create_container(
    'busybox', 'ls', ports=[5000,('31230-31250','udp'),'31230-31250'],
    host_config=cli.create_host_config(port_bindings={
        5000: 5000,
        '31230-31250/udp': [ 
            ('192.168.0.100','31230-31250'),
            ('192.168.0.101','31230-31250'),
        ],
        '31230-31250' :  [ 
            ('192.168.0.100','31230-31250'),
            ('192.168.0.101','31230-31250'),
        ]
    })
)
```

it raise error

```
docker.errors.APIError: 500 Server Error: Internal Server Error ("Invalid port specification: "31230-31250”")
```

update logic to support it as docker CLI.

### CODE REVIEW

**Comment by WheresWardy** [comment]
Is there any update on this?

**Comment by aanand** [comment]
Could you add some unit and integration tests for this? The code is also a little dense and would benefit from being split up into smaller methods.

**Comment by ijc** [comment]
PR grooming: Sorry this got left for so long without a response. It looks like this is now supported (34ea11fcb72dcf4d314f62c457d2cfab1f81ee6c is one related commit) so I'm closing. Thanks for your PR.

**Comment by arisxama** [comment]
Hey @ijc, not sure this was ever supported. Using docker-py [docker (4.2.2)] and we still get [ERROR] 400 Client Error: Bad Request ("invalid port specification: "31230-31250"").

`Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683`

**Comment by arisxama** [comment]
@vagouzhou did you ever solve this one out? Seems port range support hasn't been implemented yet for docker-py.

**Comment by vagouzhou** [comment]
I resolve it by local patch, but this PR don't be merged in official docker-py as it just be closed.
maybe few user need it :)

**Comment by remoteweb** [comment]
@vagouzhou nice! Would you mind sharing it with us? Or if you did already how can we use your commit?

**Comment by vagouzhou** [comment]
just merge commits of this PR.

**Comment by remoteweb** [comment]
What a silly question. Thanks. I havent yet compiled docker-py from src files but i guess it would be as easy as 'make; make build;'

**Pull request closed without merging**
