### PR TITLE
Use `packaging` instead of `distutils` for `Version`

### LINKED ISSUE #2928: docker.from_env produces "DeprecationWarning: distutils Version classes are deprecated" warnings.
Hello!

It would seem that setuptools v59.6.0 added a warning when using distutils version: https://github.com/pypa/setuptools/commit/1701579e0827317d8888c2254a17b5786b6b5246

So with the current setuptools, using from_env produces these warnings
```
$ PYTHONWARNINGS=default docker-warnings/bin/python
Python 3.9.9 (main, Nov 26 2021, 20:52:48)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.from_env()
/private/tmp/docker-warnings/lib/python3.9/site-packages/docker/utils/utils.py:52: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  s1 = StrictVersion(v1)
/private/tmp/docker-warnings/lib/python3.9/site-packages/docker/utils/utils.py:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  s2 = StrictVersion(v2)
<docker.client.DockerClient object at 0x10d89d9d0>
```

Just raising the flag to fix before it's too late ;) 

Thank you!

### PR DESCRIPTION
**Pull request by FrancescoCasalegno**
Fixes #2928.

## Context

`setuptools` has deprecated the usage of `distutils` `Version` classes since version `60.3.0`. See https://github.com/pypa/setuptools/commit/1701579e0827317d8888c2254a17b5786b6b5246 for details.

As a consequence, a `warning` is raised any time we try, e.g., to do `from docker import from_env`. Notice that this `warning` can be fatal if the user has set a warning filter to `error` mode, which is not too uncommon when running unit tests in CI.

## Proposed solution

1. Replace occurrences of `distutils.Version` (and its subclasses) with `packaging.Version`.
2. Add `packaging` to the `install_requires`.

### CODE REVIEW

**Comment by FrancescoCasalegno** [comment]
@aiordache @ulyssessouza this PR has been open for 2 days but the CI tests is still on hold, because it needs your approval before being run.

Could you please give your green light to run the CI workflow (and also provide some feedback on this PR, when you have time)?

**Comment by marco-m-pix4d** [comment]
Hello @aiordache @ureyes84 any chance you could have a look at the request by @FrancescoCasalegno above? Thanks!

**Comment by florian-hoenicke** [comment]
I use `import warnings` and `warnings.filterwarnings("ignore", category=DeprecationWarning)` as a workaround but it would be better if it could be fixed here.

**Comment by liadmord** [comment]
Seems like the maintainers have gone AWOL, maybe someone should fork this repo?

**Review by milas — APPROVED** [review]

**Comment by marco-m-pix4d** [comment]
Thanks @milas !

**Pull request merged**
