### PR TITLE
Remove the network mode to support linkable cantainers check

### PR DESCRIPTION
**Pull request by wenchma**
Partially related to issue docker/docker#21080

Signed-off-by: Wen Cheng Ma <wenchma@cn.ibm.com>

### CODE REVIEW

**Comment by wenchma** [comment]
The related jenkins checks failure:

    =================================== FAILURES  ===================================
    08:03:52 __________________________ LinkTest.test_remove_link  ___________________________
    08:03:52 /docker-py/tests/integration/api_test.py:57: in test_remove_link
    08:03:52     self.client.start(container2_id)
    08:03:52 /docker-py/docker/utils/decorators.py:21: in wrapped
    08:03:52     return f(self, resource_id, *args, **kwargs)
    08:03:52 /docker-py/docker/api/container.py:356: in start
    08:03:52     self._raise_for_status(res)
    08:03:52 /docker-py/docker/client.py:142: in _raise_for_status
    08:03:52     raise errors.APIError(e, response, explanation=explanation)
    08:03:52 E   APIError: 500 Server Error: Internal Server Error ("Cannot link to /elegant_lichterman,  as it does not belong to the same network with /boring_mccarthy")

**Comment by wenchma** [comment]
because it blocks the jenkins jobs of https://github.com/docker/docker/pull/21115

**Comment by shin-** [comment]
LGTM :+1:

**Comment by wenchma** [comment]
rebased

**Comment by thaJeztah** [comment]
ping @aanand @dnephin ptal :heart:

**Comment by dnephin** [comment]
LGTM

**Pull request merged**
