### PR TITLE
Allow custom pid mode

### PR DESCRIPTION
**Pull request by shin-**
Carries #1177

### CODE REVIEW

**Comment by aanand** [comment]
LGTM, needs rebase

**Comment by bfirsh** [comment]
rebased

**Comment by shin-** [comment]
The rebase is missing my changes I think. I'll reupload from my local branch.

**Comment by bfirsh** [comment]
Oh, weird. Perhaps they were cancelled out by an upstream changes? I just did `git rebase master` and resolved the doc conflict.

**Pull request merged**
