### PR TITLE
Fetch network details with network lists greedily

### LINKED ISSUE #1775: client.networks.containers() is always empty
```
>>> import docker
>>> d = docker.from_env()
>>> [n.name for n in d.networks.list()]
['pedlintegrationtests_default', 'bridge', 'host', 'none']
>>> [n.containers for n in d.networks.list()]
[[], [], [], []]
```

```
$ docker network inspect pedlintegrationtests_default | jq '.[0].Containers | length'
4
```

```
$ pip freeze | grep docker && python --version && docker version
docker==2.5.1
docker-compose==1.16.1
docker-pycreds==0.2.1
dockerpty==0.4.1
nvidia-docker-compose==0.1.4
Python 3.5.2
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### PR DESCRIPTION
**Pull request by rycus86**
This change would fix #1775 plus adds some missing documentation and input arguments around networks.

Per the comment on https://github.com/docker/docker-py/issues/1775#issuecomment-336578128 this change enables adding a `greedy=True` parameter on the model's and the API client's network list function that will inspect each network on the initial list.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Note that using API 1.25 will still return the container details; see https://github.com/moby/moby/pulls/30673

The list of containers was removed from the network _list_ because it can be a heavy operation in larger setups (many containers, many networks), (inspecting a single network still returns attached containers)

**Comment by rycus86** [comment]
Thanks for having a look at this!

I've moved the new flag to the model only and left the API client unchanged. I only added it there because of https://github.com/docker/docker-py/issues/1775#issuecomment-338863313 but it makes sense to leave the API client as it was.

@thaJeztah thanks for letting me know!
It looks like the behavior has changed in API 1.28, added a check for it and won't inspect the services if the client is on a lower version.

**Comment by rycus86** [comment]
Hi @shin- ,

Sorry I haven't done reviews on GitHub yet, is there a link/button somewhere to update that I've made the changes that were requested?

Thank you!

**Comment by rycus86** [comment]
Right, sorry, forgot about Thanksgiving! :)
Enjoy your break!

**Pull request merged**
