### PR TITLE
test: remove APT_MIRROR from Dockerfile

### PR DESCRIPTION
**Pull request by thaJeztah**
The official Python images on Docker Hub switched to debian bookworm, which is now the current stable version of Debian.

However, the location of the apt repository config file changed, which causes the Dockerfile build to fail;

    Loaded image: emptyfs:latest
    Loaded image ID: sha256:0df1207206e5288f4a989a2f13d1f5b3c4e70467702c1d5d21dfc9f002b7bd43
    INFO: Building docker-sdk-python3:5.0.3...
    tests/Dockerfile:6
    --------------------
       5 |     ARG APT_MIRROR
       6 | >>> RUN sed -ri "s/(httpredir|deb).debian.org/${APT_MIRROR:-deb.debian.org}/g" /etc/apt/sources.list \
       7 | >>>     && sed -ri "s/(security).debian.org/${APT_MIRROR:-security.debian.org}/g" /etc/apt/sources.list
       8 |
    --------------------
    ERROR: failed to solve: process "/bin/sh -c sed -ri \"s/(httpredir|deb).debian.org/${APT_MIRROR:-deb.debian.org}/g\" /etc/apt/sources.list     && sed -ri \"s/(security).debian.org/${APT_MIRROR:-security.debian.org}/g\" /etc/apt/sources.list" did not complete successfully: exit code: 2

The APT_MIRROR build-arg was originally added when the Debian package repositories were known to be unreliable, but that hasn't been the case for quite a while, so let's remove this altogether.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@milas ptal ☺️

**Review by tianon — APPROVED** [review]
:eyes:

**Review by milas — APPROVED** [review]

**Comment by thaJeztah** [comment]
LOL, guess I forgot I had this one when I opened https://github.com/docker/docker-py/pull/3166

**Comment by milas** [comment]
> LOL, guess I forgot I had this one when I opened #3166

I thought you knew every GitHub issue/PR number by heart!

**Comment by thaJeztah** [comment]
hehe, yeah, but also currently have 340 pull requests open on GitHub, so sometimes forget about some 😂 🙈

**Pull request merged**
