### PR TITLE
Add healthcheck for service

### PR DESCRIPTION
**Pull request by tossmilestone**
Support service create with healthcheck test.

Signed-off-by: He Xiaoxi <tossmilestone@gmail.com>

### CODE REVIEW

**Comment by tossmilestone** [comment]
Why the integration tests always failed with the error:
```
=================================== ERRORS ====================================
03:55:19 [py3.5_1.13.1] __________________ ERROR at setup of ServiceTest.test_create ___________________
03:55:19 [py3.5_1.13.1] tests/integration/models_services_test.py:15: in setUpClass
03:55:19 [py3.5_1.13.1]     client.swarm.init('eth0', listen_addr=helpers.swarm_listen_addr())
03:55:19 [py3.5_1.13.1] docker/models/swarm.py:96: in init
03:55:19 [py3.5_1.13.1]     self.client.api.init_swarm(**init_kwargs)
03:55:19 [py3.5_1.13.1] docker/utils/decorators.py:34: in wrapper
03:55:19 [py3.5_1.13.1]     return f(self, *args, **kwargs)
03:55:19 [py3.5_1.13.1] docker/api/swarm.py:102: in init_swarm
03:55:19 [py3.5_1.13.1]     self._raise_for_status(response)
03:55:19 [py3.5_1.13.1] docker/api/client.py:222: in _raise_for_status
03:55:19 [py3.5_1.13.1]     raise create_api_error_from_http_exception(e)
03:55:19 [py3.5_1.13.1] docker/errors.py:31: in create_api_error_from_http_exception
03:55:19 [py3.5_1.13.1]     raise cls(e, response=response, explanation=explanation)
03:55:19 [py3.5_1.13.1] E   docker.errors.APIError: 500 Server Error: Internal Server Error ("interface eth0 has more than one IPv6 address (2001:db8:1::242:ac11:2 and fe80::42:acff:fe11:2)")
```
@shin- please help to resolve it. Thanks!

**Comment by shin-** [comment]
I fixed the issue in master, please rebase your PR to get the changes :+1:

**Comment by tossmilestone** [comment]
Updated, @shin- PTAL, thanks!

**Comment by tossmilestone** [comment]
Closed since there is already a PL #1783 added this feature.

**Pull request closed without merging**
