### PR TITLE
Docs examples

### PR DESCRIPTION
**Pull request by alasdairnicol**
A couple of minor tidy ups to the examples in the docs, which make them more consistent, and avoid deprecation warnings.

### CODE REVIEW

**Comment by alasdairnicol** [comment]
My initial patch was wrong, because `create_host_config` is a regular method, not a classmethod. I've fixed the patch and pushed it again.

**Comment by shin-** [comment]
Thanks! Can you squash those into one single commit?

On a tangential note, I'm not the biggest fan of calling the client instance `cli` because of the "Command Line Interface" acronym. But we can take another pass at this later - it being consistent means it's easier to `sed` later down the line.

**Comment by alasdairnicol** [comment]
Thanks for the quick review! I've squashed into a single commit and rebased.

> I'm not the biggest fan of calling the client instance cli because of the "Command Line Interface" acronym. 

Sure, I understand. I chose `cli` because it appeared to be the most common variable name, not for any other reason.

**Comment by shin-** [comment]
LGTM!

**Comment by dnephin** [comment]
LGTM

**Pull request merged**
