### PR TITLE
Add labels and shmsize arguments to the image build

### LINKED ISSUE #1262: Build Image Missing Arguments
The build image function is missing some arguments that are present in the v1.24 api.
- shmsize - Size of /dev/shm in bytes. The size must be greater than 0. If omitted the system uses 64MB.
- labels – JSON map of string pairs for labels to set on the image.

See: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/build-image-from-a-dockerfile

### PR DESCRIPTION
**Pull request by rmb938**
Closes #1262 

Allows labeling and setting the shmsize of built images.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Could also please update documentation? https://github.com/rmb938/docker-py/blob/ac20dae89be25bdf9840640bebdf24e99e05a085/docs/api.md

**Comment by rmb938** [comment]
@TomasTomecek yup no problem, how does that look?

**Comment by TomasTomecek** [comment]
@rmb938 :+1:

**Comment by rmb938** [comment]
@shin- Is it possible that we can get this merged sometime soon?

**Comment by TomasTomecek** [comment]
Needs rebase.

**Comment by rmb938** [comment]
I've rebased this ~15 times since creating this pull request while other things have gotten merged and would like this to get merged as soon as possible. I have worked around not having this as best as I could but now it is a major blocker. @shin- I would appreciate if this can be merged and released relatively soon.

**Comment by shin-** [comment]
LGTM - thank you!

**Pull request merged**
