### PR TITLE
Add device requests

### PR DESCRIPTION
**Pull request by EpicWink**
This PR was made before teklia#1 was merged, and is now a duplicate of #2471. This introduced a fix for the failing test by creating a 1.40 client specific for that test.

Unfortunately, looks like User-Agent needs to be allowed in the request headers. Not sure why, possibly a requirement of the v1.40 API, but it could be that I'm not setting up the environment correctly.

### CODE REVIEW

**Comment by whillas** [comment]
Anything blocking this PR?

**Comment by EpicWink** [comment]
Waiting on review

**Comment by EpicWink** [comment]
My PR teklia#1 just got merged in, so now this PR is equivalent to #2471

**Comment by La0** [comment]
I'm waiting for the build to finish on #2471, then i'll add a comment there

**Pull request closed without merging**
