### PR TITLE
Simplify some unnecessarily complex file structures

### PR DESCRIPTION
**Pull request by bfirsh**

### CODE REVIEW

**Comment by bfirsh** [comment]
Rebased. /cc @docker/core-docker-py-maintainers

**Comment by dnephin** [comment]
This LGTM, but I'd like to make sure @shin- is ok with it.

**Comment by shin-** [comment]
Not against it in principle, slightly worried about breaking stuff for people who might have a `from docker.auth.auth` import or similar. May be reasonable to put it in the 2.0 milestone?

**Comment by bfirsh** [comment]
Sure! Sounds reasonable to me - it's plausible that it could break code and
it isn't urgent.

**Comment by bfirsh** [comment]
Rolled into #1186

**Pull request closed without merging**
