### PR TITLE
Add 'verbose' option for network inspect api

### PR DESCRIPTION
**Pull request by sanimej**
Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by shin-** [comment]
Thanks Santhosh! Do you know which API version introduced that option? We probably want to do a client-side check to see if it's available to the user.

**Comment by sanimej** [comment]
@shin- `verbose` option was introduced in v1.28. I will add a version check and an error message similar to what is done for other optional flags. Thanks.

**Comment by sanimej** [comment]
@shin- Added the version check. PTAL.

**Comment by shin-** [comment]
Merged via #1556

**Pull request closed without merging**
