### PR TITLE
Add unmaintained notice

### PR DESCRIPTION
**Pull request by StefanScherer**
Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>

### CODE REVIEW

**Comment by gitpushdashf** [comment]
Will the Python name be passed on, or will we need to make a fork with a new name?

**Comment by yaleman** [comment]
So... you're just not going to support it at all now?

**Comment by gaby** [comment]
@yaleman They probably just abandoning using Python, given that they have a golang docker library already. Same thing happened with Docker Compose which is now Golang based.

**Comment by StefanScherer** [comment]
Thanks for your interest and your feedback so far. It's not decided yet that we merge this PR.
One possible way is a call for maintainers. We'll keep you informed how we proceed.

**Comment by gitpushdashf** [comment]
Hi @StefanScherer!

Do you have any updates for us?

Thank you!

**Comment by david0** [comment]
Any news? It really is a pity that this great package seems to be dead-ish atm.

**Comment by gabrieldemarmiesse** [comment]
I made Python-on-whales, a Python Docker client that's much easier to maintain because it calls the Docker client binary (in go) behind the scenes. It has made the users happy so far by also providing access to buildx, compose and `docker stack deploy` (which docker-py doesn't).

[There was a blog post in the Docker blog a while ago about it](https://www.docker.com/blog/guest-post-calling-the-docker-cli-from-python-with-python-on-whales/), to do this, I talked to folks at Docker to get some guidance about the project.

Maybe we could add a note saying that this project exists and is maintained, even if we don't actively recommend it.

At least it provides an escape route for projects that heavily rely on Docker-py.

At the time of writing it has 223 stars, ~3500 downloads daily, 21 contributors, 1 core dev (me).

[Link to the documentation](https://gabrieldemarmiesse.github.io/python-on-whales/)
[Link to the Github repo](https://github.com/gabrieldemarmiesse/python-on-whales)

**Comment by sylvainmouquet** [comment]
@gabrieldemarmiesse thanks i have moved my code to your library and everything works well :)

**Comment by felixfontein** [comment]
For everyone else following this one who didn't notice, there's been a lot of activity in this repository over the last couple of days. So maybe this PR isn't needed anymore?

**Comment by StefanScherer** [comment]
We've reserved some capacity to make another release. Closing this PR. Thanks for your patience.

**Pull request closed without merging**
