### PR TITLE
Add prune_build

### PR DESCRIPTION
**Pull request by The-Loeki**
Adds https://docs.docker.com/engine/api/v1.36/#operation/BuildPrune

### CODE REVIEW

**Comment by The-Loeki** [comment]
there you go... Although I do have to say I fail to see reasoning behind the hard demand for it; after all the only reason the key is trustworthy is because I said so in GH, so if my account was compromised so would the trust be.

**Comment by The-Loeki** [comment]
@GordonTheTurtle I've added the GPG sig as per your request, but your dco-signed is apparently stuck in 'Waiting for status to be reported' or something?

**Comment by shin-** [comment]
Gordon is a bot, so it won't be able to answer ;
The thing it's requesting is for you to add the signoff line to your commit message (`git commit -s`). Using the commands it suggests should fix everything. GPG signing is a different thing entirely and isn't required.

**Comment by The-Loeki** [comment]
Yeah, but didn't I do just that?

**Comment by The-Loeki** [comment]
Guess I should've read a bit better ;) sorry about that

**Pull request merged**
