### PR TITLE
Added extra filtering options to containers command in ClientAPI

### PR DESCRIPTION
**Pull request by SakuraSound**
From #1016, I added some extra documentation notes for the containers command in ClientAPI.
Signed-off-by: Joir-dan Gumbs <jdagumbs@gmail.com>

### CODE REVIEW

**Comment by shin-** [comment]
Thanks! Do you mind rebasing this against the current `master`? Changes LGTM.

**Comment by SakuraSound** [comment]
Done

**Comment by MHBauer** [comment]
Looks more comprehensive. I see a filter for `volume` and `isolation` in the docker docs. Given windows isn't prime time yet, I think you could leave `isolation` off, but I'd like to see `volume` included.

**Comment by shin-** [comment]
Thanks!
If we expect this list will continue to grow, maybe a better solution would be to link to the source instead of trying to play catch up. Or at least add a disclaimer like "`A comprehensive list is available [here](link-docker-docs)`"

**Comment by SakuraSound** [comment]
I could probably add that at the bottom of the updated docs, and it should work as long as the link carries with each new version.

**Comment by shin-** [comment]
Ah, yeah, fair point. I don't think the docker docs have a dynamic link to the latest API docs page. Maybe we can just link to https://docs.docker.com/engine/reference/api/docker_remote_api/ for now.

**Comment by SakuraSound** [comment]
Looking at the docs link, it seems we may be able to get away with using links:

https://docs.docker.com/engine/reference/commandline/ps/ seems like it carries across versions.

**Comment by shin-** [comment]
Agreed. Do you mind making the change?

**Comment by SakuraSound** [comment]
Can do

**Comment by shin-** [comment]
Awesome, thank you!

**Pull request merged**
