### PR TITLE
Split the entrypoint string to shell-like syntax.

### PR DESCRIPTION
**Pull request by ColinHuang**
If not doing shlex for ```entrypoint``` parameter. 
Jenkin image cannot start successful.

### CODE REVIEW

**Comment by aanand** [comment]
Thanks. The tests need fixing, and it'd be good to have a test that explicitly checks the new behaviour.

**Comment by ColinHuang** [comment]
Fixed test case for ```entrypoint``` new  behaviour.

**Comment by aanand** [comment]
LGTM

**Comment by linlinlinlin** [comment]
LGTM

**Comment by shin-** [comment]
There's a lot of commits that shouldn't be here - can you try and isolate your changes and submit a clean PR? Thanks :)

**Pull request closed without merging**
