### PR TITLE
Note explicit support for Python 3.5

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
dependency updates look like a pretty big change; some of them even jump several minor releases -- it could be very beneficial to run compose's test suite with the newer deps

**Comment by felixonmars** [comment]
I can fix the flake8 errors here by adding some noqa, and will run compose's test suite soon.

Do you have any idea for the `E   docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Invalid signal: Signals.SIGKILL'")` failure in janky? I tried a bit but it's still strange :(

**Comment by graingert** [comment]
fixed in https://github.com/docker/docker-py/pull/1071

**Comment by graingert** [comment]
@felixonmars with a better approach to the flake8 errors

**Comment by felixonmars** [comment]
Thank you :)

**Comment by shin-** [comment]
Thank you for your help! This has been fixed by #1071, and I will close this issue as a result.

**Pull request closed without merging**
