### PR TITLE
Workaround requests resolving our unix socket URL on macosx.

### PR DESCRIPTION
**Pull request by mnottale**
Signed-off-by: Matthieu Nottale <matthieu.nottale@docker.com>

### CODE REVIEW

**Comment by mnottale** [comment]
Fixes docker-compose issue https://github.com/docker/compose/issues/3419

**Comment by shin-** [comment]
@mnottale Thanks! You were able to verify that this fixes the issue?

**Comment by mnottale** [comment]
Yes I did using tcpdump. I can confirm no DNS queries with this patch (and one per docker connection without)

**Comment by shin-** [comment]
Cool, thank you! Maybe we'll make a 3.1.1 - this fix will make a lot of people happy.

**Pull request merged**
