### PR TITLE
Add documentation to argument 'mem_reservation' in ContainerCollection::run

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hello.

I tried to run container with a soft limit using docker-py and I discovered that mem_reservation works but is not documented.
I just added a simple comment in the doc string to help other people gain some time. Maybe I should have write more to explain what is the soft limit?

I ran make docs and succeeded but I failed to run make test. Here is the log I got:
```
NTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 203, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 242, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 252, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 466, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 250, in check_pending
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> PluginValidationError: unknown hook 'pytest_funcarg__cov' in plugin <module 'pytest_cov.plugin' from '/usr/local/lib/python2.7/site-packages/pytest_cov/plugin.py'>
```

Good bye.

### CODE REVIEW

**Comment by shin-** [comment]
Thanks! Can you

- Rebase this against the current master branch (should take care of the failures you're seeing and the ones in the CI)
- Add it to the documentation of `APIClient.create_host_config` as well?

**Comment by eiffel-fl** [comment]
I did what you asked.
The `make test` ran more test but some failures were met:
```
============================================================== FAILURES ===============================================================
__________________________________________ AttachContainerTest.test_attach_stream_and_cancel __________________________________________
tests/integration/api_container_test.py:1275: in test_attach_stream_and_cancel
    for line in output:
docker/types/daemon.py:32: in __next__
    return next(self._stream)
docker/api/client.py:404: in <genexpr>
    gen = (data for (_, data) in gen)
docker/utils/socket.py:83: in <genexpr>
    return ((STDOUT, frame) for frame in frames_iter_tty(socket))
docker/utils/socket.py:115: in frames_iter_tty
    result = read(socket)
docker/utils/socket.py:31: in read
    select.select([socket], [], [])
E   Failed: Timeout >5.0s
____________________________________________ ImageCollectionTest.test_list_with_repository ____________________________________________
docker/api/client.py:256: in _raise_for_status
    response.raise_for_status()
/usr/local/lib/python3.6/site-packages/requests/models.py:940: in raise_for_status
    raise HTTPError(http_error_msg, response=self)
E   requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://docker:2375/v1.35/images/create?tag=latest&fromImage=alpine

During handling of the above exception, another exception occurred:
tests/integration/models_images_test.py:64: in test_list_with_repository
    image = client.images.pull('alpine:latest')
docker/models/images.py:437: in pull
    repository, tag=tag, stream=True, **kwargs
docker/api/image.py:400: in pull
    self._raise_for_status(response)
docker/api/client.py:258: in _raise_for_status
    raise create_api_error_from_http_exception(e)
docker/errors.py:31: in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
E   docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: EOF")
======================================================= short test summary info =======================================================
XFAIL tests/integration/api_container_test.py::CreateContainerTest::test_create_with_cpu_rt_options
  CONFIG_RT_GROUP_SCHED isn't enabled
XFAIL tests/integration/api_container_test.py::CreateContainerTest::test_create_with_init_path
  init-path removed in 17.05.0
XFAIL tests/integration/api_swarm_test.py::SwarmTest::test_init_swarm_with_log_driver
  This doesn't seem to be taken into account by the engine
SKIP [1] tests/integration/api_image_test.py:290: Doesn't work inside a container - FIXME
SKIP [1] /src/tests/integration/api_swarm_test.py:31: Test stalls the engine on 1.12.0
=============================== 2 failed, 348 passed, 2 skipped, 3 xfailed, 3 xpassed in 486.94 seconds ===============================
Makefile:74 : la recette pour la cible « integration-dind-ssl » a échouée
make: *** [integration-dind-ssl] Erreur 1
```

The `make docs` succeeded but 2 warnings were met.

**Comment by eiffel-fl** [comment]
I forgot to add my local changes before amen my commit...
Things should be good now!

**Comment by thaJeztah** [comment]
Looks like it needs to be rebased again, @eiffel-fl  😢

**Comment by eiffel-fl** [comment]
Normally it should be good!

**Comment by thaJeztah** [comment]
Oh! Looks like you did a merge, which causes a merge-commit to be in this PR.

We like to keep the git history clean, and usually do a `git rebase` (and if needed, squash commits).


I'm not a maintainer here (perhaps they use the "squash merge" option that GitHub provides), but if you have time, could you rebase and squash your commits?

Let me try to describe what's needed;

I'm assuming your remotes are configured to have `upstream` point to this repository, and `origin` to your repository, but you can check that using `git remote -v`, which should look something like this:

```bash
git remote -v

origin	https://github.com/eiffel-fl/docker-py.git (fetch)
origin	https://github.com/eiffel-fl/docker-py.git (push)
upstream	https://github.com/docker/docker-py.git (fetch)
upstream	https://github.com/docker/docker-py.git (push)
```


If that looks the same on your machine, you can do an interactive rebase to "squash" your commits, and to get rid of the merge commit.

To do so:

1. Make sure your upstreams are up-to-date

```bash
git fetch --all 
```

2. Start an interactive rebase to rebase your branch;

```bash
git rebase -i upstream/master
```
 
This will open an editor showing all the commits that are in your branch but not in the "upstream". The merge commit should automatically disappear;

```
pick 65ce939 Add documentation to argument 'mem_reservation'.
pick 1768bb9 Add documentation to argument 'mem_reservation'.

# Rebase 068ddf8..bcf7889 onto 068ddf8 (2 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

To squash the remaining commits, you *edit* the file, and mark the second commit to be squash into the first one.

To do so; change the second `pick` to `squash` (or `s`);

```
pick 65ce939 Add documentation to argument 'mem_reservation'.
squash 1768bb9 Add documentation to argument 'mem_reservation'.
```

Now, save the file and exit the editor

A new editor will show, allowing you to edit the commit message (which is now a combination of the two commits);

```
# This is a combination of 2 commits.
# This is the 1st commit message:

Add documentation to argument 'mem_reservation'.

The documentation was added for function ContainerCollection::run and
ContainerApiMixin::create_host_config.
...
```

Modify the message (if needed), save the file, and exit your editor


Git will now complete the rebase;

```
[detached HEAD 93a99e6] Add documentation to argument 'mem_reservation'.
 Author: Francis Laniel <francis.laniel@lip6.fr>
 Date: Wed Jan 9 19:31:56 2019 +0100
 2 files changed, 2 insertions(+), 1 deletion(-)
Successfully rebased and updated refs/heads/pull_2217.
```


If you completed that successfully, you need to _force_ push your changes. Doing so will update the pull request with your latest version;


```bash
git push -f origin
```


You should now be done :+1:

**Comment by eiffel-fl** [comment]
I squash the two commits.

I did not know why I had to do a merge... But when I tried to push to my remote it said there was a problem so I needed to merge my remote branch with my local branch.

**Comment by thaJeztah** [comment]
Thanks!

@shin- ptal

**Comment by shin-** [comment]
LGTM, thanks!

**Comment by eiffel-fl** [comment]
Thank you :D

**Pull request merged**
