### PR TITLE
Hostname IP matching

### LINKED ISSUE #706: hostname 'w.x.y.z' doesn't match 'boot2docker', even though 'w.x.y.z' is allowed by the certificate
This may be a dup of #406, but I don't think that's fixed (yes, there's an [`/etc/hosts` hack/work-around](https://github.com/docker/docker-py/blob/master/docs/boot2docker.md), but it doesn't address the underlying issue). You can see this when doing the following:

```sh
% mkdir -p foo
% virtualenv foo
...
% cd foo
% . ./bin/activate
% pip install requests==2.2.1 # it was suggested that >=2.5.0 was a cause
...
% pip install docker-py
...
% unset DOCKER_CERT_PATH DOCKER_HOST DOCKER_TLS_VERIFY
% export DOCKER_HOST=tcp://10.68.69.86:2376
% export DOCKER_TLS_VERIFY=0
% export DOCKER_CERT_PATH="${HOME}/.docker"
% cat >test.py
```

```py
from docker import AutoVersionClient
from docker.utils import kwargs_from_env
dc = AutoVersionClient(**kwargs_from_env())
```
```sh
^D
% python test.py
python test.py
Traceback (most recent call last):
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 172, in connect
    self.assert_hostname or self.host)
  File "/Users/xyz/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 289, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname '10.68.69.86' doesn't match 'boot2docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../foo/lib/python3.4/site-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File ".../foo/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 508, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: hostname '10.68.69.86' doesn't match 'boot2docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 65, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File ".../foo/lib/python3.4/site-packages/docker/client.py", line 837, in version
    return self._result(self._get(url), json=True)
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File ".../foo/lib/python3.4/site-packages/requests/sessions.py", line 395, in get
    return self.request('GET', url, **kwargs)
  File ".../foo/lib/python3.4/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File ".../foo/lib/python3.4/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File ".../foo/lib/python3.4/site-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname '10.68.69.86' doesn't match 'boot2docker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dc = AutoVersionClient(**kwargs_from_env())
  File ".../foo/lib/python3.4/site-packages/docker/client.py", line 863, in __init__
    super(AutoVersionClient, self).__init__(*args, **kwargs)
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 53, in __init__
    self._version = self._retrieve_server_version()
  File ".../foo/lib/python3.4/site-packages/docker/clientbase.py", line 73, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: hostname '10.68.69.86' doesn't match 'boot2docker'
```

But `docker ps` works fine and `10.68.69.86` is listed in the server certificate:

```sh
% DOCKER_TLS_VERIFY=0 docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
% DOCKER_TLS_VERIFY=1 docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
% ssh docker@10.68.69.86 sudo openssl x509 -in /var/lib/boot2docker/tls/server.pem -text
docker@10.68.69.86's password:
Certificate:
    Data:
        ...
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:boot2docker, IP Address:127.0.0.1, IP Address:10.211.55.253, IP Address:10.68.69.86
...
```

What's weird (maybe) is that this works (partially):

```sh
% cat >test2.py
```

```py
from os import environ
from os.path import join as ospath_join
try:
    from urllib.parse import ( # pylint: disable=no-name-in-module
        urlparse,
        urlunparse,
    )
except ImportError:
    from urlparse import ( # pylint: disable=no-name-in-module
        urlparse,
        urlunparse,
    )
from docker import AutoVersionClient
from docker.tls import TLSConfig
from docker.utils.utils import DEFAULT_UNIX_SOCKET
DOCKER_CERT_PATH = environ.get('DOCKER_CERT_PATH', None)
DOCKER_HOST = environ.get('DOCKER_HOST', DEFAULT_UNIX_SOCKET)
DOCKER_TLS_VERIFY = environ.get('DOCKER_TLS_VERIFY', None)

if DOCKER_CERT_PATH:
    docker_host = urlparse(DOCKER_HOST)
    DOCKER_HOST = urlunparse(( 'https', ) + docker_host[1:])

    tls_config_args = {
        'client_cert': (
            ospath_join(DOCKER_CERT_PATH, 'cert.pem'),
            ospath_join(DOCKER_CERT_PATH, 'key.pem'),
        ),
    }

    if DOCKER_TLS_VERIFY is not None:
        tls_config_args['verify'] = ospath_join(DOCKER_CERT_PATH, 'ca.pem') if DOCKER_TLS_VERIFY != '0' else False

    tls = TLSConfig(**tls_config_args)
else:
    tls = False

dc = AutoVersionClient(DOCKER_HOST, tls=tls)
```

```sh
^D
% python test2.py # works, but
% DOCKER_TLS_VERIFY=1 python test2.py # fails with hostname '10.68.69.86' doesn't match 'boot2docker' like above
...
```

### LINKED ISSUE #731: requests.exceptions.SSLError: no appropriate commonName or subjectAltName fields were found
Failing to connect to a local `docker-machine` machine using the virtualbox driver via some code that is using `docker.utils.kwargs_from_env`. It's proving difficult to track down but considering the `docker` cli and `docker-machine` are operating happily this must be an issue with the python bindings.

The shell has been activated with `eval "$(docker-machine env default)"` which results in the following vars being set:

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.103:2376"
export DOCKER_CERT_PATH="/Users/michael/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval "$(docker-machine env default)"
```

An example cert is here and there is no `commonName` or `subjectAltName`, but again the docker cli works fine for running instances so I imagine it is somewhere in docker-py interacting with requests and urllib3.

```
❯ openssl x509 -in ~/.docker/machine/certs/cert.pem -text -noout                                                                                                    marina/git/master
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            9d:8a:82:0e:b8:78:8e:04:69:5b:55:55:ce:43:ac:32
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=michael
        Validity
            Not Before: Aug 24 19:37:00 2015 GMT
            Not After : Aug  8 19:37:00 2018 GMT
        Subject: O=michael
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:9b:25:7b:cb:20:d4:b7:4c:ee:d2:4c:4b:4f:2c:
                    c6:56:73:d6:dd:fc:5d:0a:0b:0b:36:2f:07:fd:90:
                    3f:be:e7:f1:26:d7:8c:59:31:71:4b:a1:c1:86:ed:
                    25:67:a0:d5:e8:e7:d6:29:24:5b:4e:52:27:61:2a:
                    53:eb:e8:59:2e:14:b8:79:51:5e:2d:50:d6:62:15:
                    bf:43:0a:bb:67:28:72:2c:98:db:64:a6:db:bb:4a:
                    c8:25:e7:76:92:2d:b1:ea:f1:c3:fb:c3:4c:c5:8f:
                    50:e6:97:86:b0:09:71:67:2d:9f:cb:47:54:8b:3c:
                    8b:23:1b:4c:da:59:9d:6b:20:9f:5b:48:89:fd:ab:
                    20:53:36:16:b9:d4:a9:77:28:b4:d8:ed:5f:2c:6f:
                    17:12:b7:2d:4d:18:39:b1:a9:39:53:db:e0:da:40:
                    15:55:17:e3:60:11:51:24:6d:c7:44:96:2a:d6:32:
                    0e:46:60:d6:65:9b:8c:86:af:6b:53:40:8a:f7:9e:
                    af:bc:32:56:db:9a:26:8a:86:07:a1:88:96:e2:a9:
                    13:fe:d8:cd:3f:a5:63:0e:81:d8:53:f3:0d:96:de:
                    50:ca:5f:09:97:18:e9:5d:46:d3:d0:a4:21:78:4d:
                    2b:0f:d6:6e:e8:d9:99:12:a4:b3:70:da:21:db:9d:
                    fc:db
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
    Signature Algorithm: sha256WithRSAEncryption
        02:2c:90:59:cd:7c:8f:7d:f6:f4:ca:e6:67:17:de:f2:83:9d:
        5d:50:d6:76:0f:25:10:4b:67:87:3e:24:18:2f:82:a1:34:7d:
        95:f9:d9:d2:fd:06:02:61:0b:8f:ff:51:c7:0a:ce:87:07:c9:
        d6:e9:b6:ec:d9:9f:6b:1a:3f:a7:4c:4b:dd:b1:a7:93:d0:2a:
        3e:44:65:bb:f2:d8:b8:d6:d9:77:42:c8:ac:ef:59:97:a5:dd:
        60:9d:80:e4:e4:da:5f:8d:9c:9c:0b:09:a5:e6:e9:cc:73:8d:
        66:fb:01:25:7d:00:b7:6e:30:71:97:df:3e:84:2c:34:6a:20:
        09:26:7e:3b:30:93:ec:95:6b:04:22:2e:77:23:8a:a1:e4:c6:
        4b:4f:be:8c:7b:32:c2:3d:77:69:83:ed:98:98:4c:f6:99:f8:
        9a:be:2c:9c:ad:69:c4:07:7a:91:69:1e:2f:80:be:bf:7b:4f:
        1e:2f:7c:a9:3b:c4:15:fb:88:42:97:92:d7:f2:4d:78:f7:15:
        4d:07:18:78:98:80:6b:12:4c:f7:96:2c:09:bf:78:69:33:a7:
        36:16:00:54:f9:81:cc:25:08:60:d1:2f:41:d4:f0:be:70:1d:
        0f:05:7c:2f:0d:b0:d1:ad:60:3c:5f:a1:d9:a0:9e:41:91:95:
        4e:37:06:62
```

I should note that everything was happy when using `boot2docker`!

The observed exception is below:

```
Traceback (most recent call last):
  File "/Users/michael/work/oss/marina/env/bin/marina", line 11, in <module>
    sys.exit(main())
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/marina/cli.py", line 198, in main
    return cli.run(argv)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/subparse/__init__.py", line 162, in run
    return self.dispatch(args, context=context)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/subparse/__init__.py", line 145, in dispatch
    return method(context, args) or 0
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/marina/build.py", line 76, in main
    builder.run()
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/marina/build.py", line 250, in run
    if not self._get_image('busybox'):
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/marina/build.py", line 348, in _get_image
    self.client.inspect_image(name)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/docker/utils/decorators.py", line 20, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/docker/client.py", line 489, in inspect_image
    self._url("/images/{0}/json".format(image.replace('/', '%2F')))
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/docker/clientbase.py", line 86, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/michael/work/oss/marina/env/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: no appropriate commonName or subjectAltName fields were found
```

### PR DESCRIPTION
**Pull request by shin-**
See discussion in https://github.com/docker/compose/pull/3226

Fixes #731
Fixes #706

### CODE REVIEW

**Comment by endophage** [comment]
Thank you! ssl_match_hostname.py` plus tests LGTM. Can't speak to the requirements changes et al.

**Comment by aanand** [comment]
Does this also mean we can stop passing `assert_hostname=False` in Compose's [docker_client.py](https://github.com/docker/compose/blob/b99037b4a61e10c9377dd707e35860cec298a268/compose/cli/docker_client.py#L54), since the IP addresses of Machine VMs will now be correctly matched?

LGTM

**Comment by tombee** [comment]
Awesome work @shin-!

**Comment by FiloSottile** [comment]
This seems not to work for me on OS X.

https://gist.github.com/FiloSottile/d308789cc7a8f1de8f36a127ecfbff19

The version is 1.8.0, the CLI works, the certificate has the IP on it, but it still raises `requests.exceptions.SSLError: hostname '192.168.64.6' doesn't match 'localhost'`

**Comment by FiloSottile** [comment]
Interestingly, patching the function to print the certificate yields

```
{'subjectAltName': [('DNS', 'localhost')], 'subject': ((('commonName', None),),)}
```

so it's a parsing problem, not a matching one. I'll open a new issue.

**Pull request merged**
