### PR TITLE
Better support for .dockerignore

### PR DESCRIPTION
**Pull request by aanand**
Builds on @mikexstudios' work in #604, with fixes for Python 2.6 and some refactoring.

Still waiting on version 0.3.4 of pathspec, though - any word on that, @cpburnz?

### CODE REVIEW

**Comment by aanand** [comment]
Test setup is failing for Python 3.2 on [this line](https://github.com/cpburnz/python-path-specification/blob/88d88fa1f04e19c6ddfad099a4d662bb63fd21f4/pathspec/__init__.py#L11), which is odd.

```
  Cloning git://github.com/cpburnz/python-path-specification.git to ./.tox/py32/src/pathspec
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/home/travis/build/docker/docker-py/.tox/py32/src/pathspec/setup.py", line 6, in <module>
        from pathspec import __author__, __email__, __license__, __project__, __version__
      File "pathspec/__init__.py", line 11
        __copyright__ = u"Copyright © 2013-2015 Caleb P. Burns"
                                                               ^
    SyntaxError: invalid syntax
```

**Comment by cpburnz** [comment]
@aanand The syntax error is due to Python 3.0&ndash;3.2 not supporting explicit unicode literals which were re-added to Python 3.3 with [PEP 0414](https://www.python.org/dev/peps/pep-0414/).

**Comment by cpburnz** [comment]
@aanand The Python 3.2 syntax error has been fixed and pathspec 0.3.4 has been released.

**Comment by aanand** [comment]
OK, after some investigation it turns out that pathspec isn't right for us. `.dockerignore`'s syntax and semantics are dramatically different from `.gitignore`s.

I've written a fairly comprehensive test suite that covers the correct behaviour (which I  confirmed was correct by testing it against actual `docker build` invocations), and updated the code accordingly. There are no new external dependencies.

Here's what's new:

- Support all basic pattern forms: file, directory, `*`, `?`, `!`

- Fix handling of wildcard patterns and subdirectories - `*/a.py` should match `foo/a.py`, but not `foo/bar/a.py`

- Fix handling of directory patterns with a trailing slash - make sure they're handled equivalently to those without one (#581)

- Fix handling of custom Dockerfiles - make sure they go in the tarball (#730)

This is ready for review.

**Comment by aanand** [comment]
@cpburnz thanks for responding, by the way, and sorry we didn't end up using your library in the end!

**Comment by aanand** [comment]
Fixed the build.

**Comment by shin-** [comment]
LGTM - thanks!

**Pull request merged**
