### PR TITLE
support MemoryReservation and KernelMemory

### PR DESCRIPTION
**Pull request by yank1**
add MemoryReservation and KernelMemory support in create_host_config

#1128

### CODE REVIEW

**Comment by aanand** [comment]
You've got some style errors (you can test this locally with `tox -e flake8`):

```
tests/unit/utils_test.py:123:80: E501 line too long (81 > 79 characters)
tests/unit/utils_test.py:132:1: E302 expected 2 blank lines, found 1
```

**Comment by yank1** [comment]
HI @aanand  , it has been fixed

**Comment by aanand** [comment]
Thanks. Can you squash and rebase please?

**Comment by shin-** [comment]
Squashed and merged into master. Thanks!

**Pull request closed without merging**
