### PR TITLE
840 add exception utility method for create host config

### LINKED ISSUE #840: [enhancement] Add utility method to utils.py for raising errors
PR incoming...

### PR DESCRIPTION
**Pull request by lots0logs**
Fixes #840

### CODE REVIEW

**Comment by lots0logs** [comment]
@shin- @dnephin

**Comment by aanand** [comment]
LGTM

**Comment by dnephin** [comment]
LGTM, but I think it needs a rebase.

It might be that the gihub "branch protection" is preventing me from merging this because I'm not an owner on this repo.

**Comment by lots0logs** [comment]
@dnephin

**Comment by lots0logs** [comment]
@dnephin @aanand @shin- :wink:

**Pull request merged**
