### PR TITLE
Redux added arguments to create a swarm with a custom address pool and subnet size.

### LINKED ISSUE #2200: No option to initialize a swarm with a default-addr-pool
The docker cli has options (available since API v1.39) to initialize a swarm with --default-addr-pool and --default-addr-pool-mask-length.  This project does not, yet.

### PR DESCRIPTION
**Pull request by hannseman**
This PR completes the work started in https://github.com/docker/docker-py/pull/2201 and https://github.com/docker/docker-py/pull/2261.

Fixes #2201
Fixes #2261
Fixes #2200

cc @bluikko

### CODE REVIEW

**Comment by hannseman** [comment]
I’ll have a look at why the test `test_attach_stream_and_cancel` failed.

**Comment by hannseman** [comment]
Had some trouble adding @bluikko as Co-Author of the commit. Hence all the force-pushes.

**Comment by ijc** [comment]
Thanks @bluikko and @hannseman!

**Comment by hannseman** [comment]
@ijc @chris-crone thanks for the review and merge!

**Comment by bluikko** [comment]
Thank you @ijc @hannseman for making it happen, my first attempt at githib was puny but I hope it at least brought some attention to this request.

**Pull request merged**
