### PR TITLE
volumes,create: support adding labels

### LINKED ISSUE #1102: Support create volume Labels options
First, check the remote API:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/

     {
      "Name": "tardis",
      "Labels": {
        "com.example.some-label": "some-value",
        "com.example.some-other-label": "some-other-value"
      },
    }

It provides ``Labels`` options. But docker-py doesn't support it right not.

Second, in docker-py's document give the following example:

    volume = cli.create_volume(
      name='foobar', driver='local', driver_opts={'foo': 'bar', 'baz': 'false'}

    docker.errors.APIError: 500 Server Error: Internal Server Error ("create foobar: invalid option key: "foo"")

But driver_opts is not working. What kinds of driver_opts can we use?

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #1102

### CODE REVIEW

**Comment by TomasTomecek** [comment]
jenkins build seems to be broken or something

**Comment by shin-** [comment]
Thanks! Can we mention the parameter in the docs (`docs/api.md`) ?

**Comment by TomasTomecek** [comment]
done (also fixed a test)

**Comment by shin-** [comment]
Thank you, LGTM!

**Comment by TomasTomecek** [comment]
rebased

**Comment by TomasTomecek** [comment]
rebased

**Comment by dnephin** [comment]
LGTM

**Comment by TomasTomecek** [comment]
can we merge now since this has 2 lgtms already? rebasing is not the most fun stuff in the world

**Comment by dnephin** [comment]
Cool, missed the earlier one

**Comment by TomasTomecek** [comment]
thanks Daniel

**Pull request merged**
