### PR TITLE
Fix #3153 - Validate tag before build using OCI regex

### LINKED ISSUE #3153: build images with tag with https prefix never ends
## Reproduces

```
docker_client = docker.from_env()
docker_client .images.build(path="{my-path}", tag="https://dummy:latest", dockerfile="{dockerfile-path})
```

Using the debugger, we can see it loop on the _post request here:

https://github.com/docker/docker-py/blob/84414e343e526cf93f285284dd2c2c40f703e4a9/docker/api/build.py#L264-L271

### PR DESCRIPTION
**Pull request by LombardiDaniel**
Fix #3153, but guarantees that it woud raise the appropriate error.

The regex expression is:
`^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127})?$`

I made it by combining `^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*` and the `(:[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127})?` group. Both expressions are from the [opencontainers/distribution-spec](https://github.com/opencontainers/distribution-spec) repo, as cited in the [docker docs](https://docs.docker.com/engine/reference/commandline/tag/).

I also wrote a test for testing a build function call with erroneous tag value.

### CODE REVIEW

**Review by milas — COMMENTED** [review]
Thanks for the PR! I just kicked off CI and there's some failures - once those are taken care of, I'll get this merged:
* Lint errors - `make ruff` (will run inside Docker container)
* Unit tests (need to update example tag) - `make unit-test-py3` (will run inside Docker container)

Let me know if you have any trouble

**Comment by LombardiDaniel** [comment]
@milas Done! the error was due to me changing the exception type and not updating the test!

**Review by milas — APPROVED** [review]
👍🏻 

Out of curiosity, was it you or the linter that reformatted the test file? (Not a big deal, just surprised)

**Comment by LombardiDaniel** [comment]
No no, i had made a change to better represent the error, before it was `TypeError` but changed to `errors.DockerException` to better represent the scenario. But had forgotten to change the test accordingly

**Comment by consideRatio** [comment]
I opened https://github.com/docker/docker-py/issues/3240 related to this PR

**Pull request merged**
