### PR TITLE
Upgrade requests to latest version

### LINKED ISSUE #1203: Issue with requests dependency
I found that commit 95d9306d2a1fd22dffb12a0548abf2d2f744ed9d excludes requests 2.11 for a bug that is fixed now on requests 2.11.1. And that's giving me a version conflict with another of the modules on my project:

```
pkg_resources.ContextualVersionConflict: (requests 2.11.1 (..............), Requirement.parse('requests<2.11,>=2.5.2'), {'docker-py'})
```

Can we allow requests 2.11.1 ?

### PR DESCRIPTION
**Pull request by dajose**
This closes #1203

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by dajose** [comment]
thanks :)

For the milestone you set, I understand this goes live until release 1.11.0. is that correct?

**Comment by shin-** [comment]
@dajose Yes, that would be released in 1.11, unless another patch version comes out inbetween in which case we might include that change as well.

Thank you for your help!

**Comment by dajose** [comment]
thanks shin-  :)

**Comment by PierreR** [comment]
Thanks for the PR !

If I am not mistaken, this is currently blocking the upgrade from docker-compose from 1.8 to 1.8.1. from pypi.

@dajose Is there a possibility to get this fix sooner in a 1.10.4 release ?

**Comment by dajose** [comment]
Hi @PierreF, actually I am not on the admin team for this project :S 

I also would like that release sooner :P

**Comment by PierreR** [comment]
Sorry wrong ping (I have just updated my comment ;-)

**Pull request merged**
