### PR TITLE
Add optional auth config to docker push

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by kmala** [comment]
@aanand can you look into this?

**Comment by aanand** [comment]
Thanks for this. Looks sound, but needs tests.

**Comment by kmala** [comment]
I had added tests.Can you look into this again

**Comment by aanand** [comment]
Great!

LGTM

**Comment by dnephin** [comment]
LGTM, might need a rebase

**Comment by kmala** [comment]
@dnephin rebased

**Comment by kmala** [comment]
in which release can i expect this to be in?

**Comment by shin-** [comment]
This will be in 1.10

**Comment by kmala** [comment]
Thanks!! Any tentative date for the release?

**Pull request merged**
