### PR TITLE
Call Client.create_host_config because the old call is deprecated

### LINKED ISSUE #737: Errors from integration test after #732
Example:

````
docker run -e NOT_ON_HOST=true -v `test -n "" && echo  || echo /tmp`:/tmp -v /var/run/docker.sock:/var/run/docker.sock docker-py python tests/integration_test.py
..........EEEEs.EE...........s............E.........E...E...........
======================================================================
ERROR: runTest (__main__.TestCreateContainerReadOnlyFs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/integration_test.py", line 281, in runTest
    read_only=True, network_mode='none'
  File "/usr/local/lib/python2.7/site-packages/docker/utils/utils.py", line 405, in create_host_config
    'docker.utils.create_host_config() is deprecated. Please use '
UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.

======================================================================
ERROR: runTest (__main__.TestCreateContainerWithBinds)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/integration_test.py", line 185, in runTest
    binds=binds, network_mode='none'
  File "/usr/local/lib/python2.7/site-packages/docker/utils/utils.py", line 405, in create_host_config
    'docker.utils.create_host_config() is deprecated. Please use '
UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
...
````

I believe this is caused by #732 deprecating the call.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #737

### CODE REVIEW

**Comment by aanand** [comment]
Thanks. LGTM

**Comment by shin-** [comment]
Thanks!

**Comment by rade** [comment]
IIRC this isn't the first time the integration tests got broken. @shin- @aanand How can we prevent future occurrences of this? Could you set up some CI that runs the integration tests on PRs?

**Comment by aanand** [comment]
@rade I'm working on it :+1:

**Pull request merged**
