### PR TITLE
Improvements to import_image() function

### PR DESCRIPTION
**Pull request by ssssam**
I've been looking at https://github.com/docker/docker-py/issues/322 and these are the various fixes I've come up with so far.

All types of import now work except for importing from a stream (by which I mean: a file-like object which Requests is unable to determine the length of). We need to use HTTP chunked transfer encoding for this (since it might be too big to read the whole thing into memory at once) but the connection gets closed after the first chunk. This may be a bug in Requests or Docker rather than docker-py.

I added integration tests for the import_image() function. All pass except for TestImportFromStream. Without the changes in this branch, all tests fail other than TestImportFromURL, with the following output:

    ======================================================================
    ERROR: runTest (tests.integration_test.TestImportFromBytes)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/integration_test.py", line 894, in runTest
        src=content, repository='test/import-from-bytes')
      File "docker/client.py", line 660, in import_image
        fic = open(src)
    TypeError: file() argument 1 must be encoded string without NULL bytes,
    not str

    ======================================================================
    ERROR: runTest (tests.integration_test.TestImportFromFile)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/integration_test.py", line 910, in runTest
        src=tar_filename, repository='test/import-from-file')
      File "docker/client.py", line 669, in import_image
        return self._result(self._post(u, data=data, params=params))
      File "docker/client.py", line 79, in _post
        return self.post(url, **self._set_request_timeout(kwargs))
      File "/usr/lib/python2.7/site-packages/requests/sessions.py", line
    425, in post
        return self.request('POST', url, data=data, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests/sessions.py", line
    383, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/site-packages/requests/sessions.py", line
    486, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests/adapters.py", line
    330, in send
        timeout=timeout
      File
    "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py",
    line 480, in urlopen
        body=body, headers=headers)
      File
    "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py",
    line 285, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "docker/unixconn/unixconn.py", line 53, in request
        super(UnixHTTPConnection, self).request(method, url, **kwargs)
      File "/usr/lib64/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib64/python2.7/httplib.py", line 827, in _send_output
        msg += message_body
    MemoryError

    ======================================================================
    ERROR: runTest (tests.integration_test.TestImportFromStream)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/integration_test.py", line 928, in runTest
        src=tar_stream, repository='test/import-from-stream')
      File "docker/client.py", line 660, in import_image
        fic = open(src)
    TypeError: coercing to Unicode: need string or buffer, instance found

### CODE REVIEW

**Comment by shin-** [comment]
Thanks! I'll look into this soon.

**Comment by Julian** [comment]
+1, `import_image` currently doesn't seem to work at all on file-like objects, large or otherwise.

**Comment by linlinlinlin** [comment]
+1

**Comment by linlinlinlin** [comment]
+1  @ssssam  thanks @shin thanks for your contribution.

**Comment by ColinHuang** [comment]
+1

**Comment by shin-** [comment]
Woah, sorry it took so long. -.- Thanks again!

**Pull request merged**
