### PR TITLE
Add missing options to the events command

### PR DESCRIPTION
**Pull request by ggtools**
- Add since, until and filters parameters to `Client.events`
- Add missing `events`command in the documentation

Signed-off-by: Christophe Labouisse <christophe@labouisse.org>

### CODE REVIEW

**Comment by shin-** [comment]
Hi, thanks for contributing! This looks good, my only issue is that, if I understand correctly, this would break for people currently using the events endpoint because of the different output format (strings VS dicts). Can we maybe add the decoding on the fly as an option, and leave the default as is to avoid breaking?

Thanks!

**Comment by ggtools** [comment]
Yes you're definitely right I adding this to the PR right now.

**Comment by shin-** [comment]
Awesome, thanks! LGTM.

**Comment by abhat** [comment]
@ggtools and @shin- , this is of huge help. Should the docs/api.md document a dictionary of non-unicode strings if decode is None and the current version if True? If you agree, I will make the edit so that the documentation is more complete.

**Pull request merged**
